spring:
  application:
    name: bff-service

server:
    port: 8084

jwt:
  secret: L6IzREsOh6XEAndJnEvkvXPuO6NvZYXNPpZ8unTwBoQ
  expiration-ms: 86400000

services:
  user:
    url: http://localhost:8081

  account:
    url: http://localhost:8082

  transaction:
    url: http://localhost:8083
